 sources:
    - name: raw
      schema: gz_raw_data
      tables:
       - name: sales
         identifier: raw_gz_sales
         description: sales of Greenweez / we have on row per productid found in each orders_id
         columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: foreign key to ship
           - name: pdt_id
             description: foreign key to product
           - name: revenue
             description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
           - name: quanitity
             description: the quantity of products purchased for a given order
         tests:
           - unique:
               column_name: "(orders_id || '-' || pdt_id)"
           

       - name: product
         identifier: raw_gz_product
         description: products of Greenweez
         columns :
         - name: products_id
           description: Primary key
           tests:
            - unique
            - not_null

       - name: ship
         identifier: raw_gz_ship
         description: shipping data for Greenweez orders
         columns:
            - name: orders_id
              description: Primary key
              tests:
               - unique
               - not_null


    
       - name: adwords
         identifier: raw_gz_adwords
         columns : 
         - name: date_date
         - name: paid_source
         - name: campaign_key
         - name: camPGN_name 
         - name: ads_cost
         - name: impression
         - name: click
         tests:
          - unique:
              column_name: "(date_date || '-'|| campaign_key)"
          - not_null:
              column_name: "(date_date || '-'|| campaign_key)"


       - name: bing
         identifier: raw_gz_bing
         columns : 
         - name: date_date
         - name: paid_source
         - name: campaign_key
         - name: camPGN_name 
         - name: ads_cost
         - name: impression
         - name: click
         tests:
          - unique:
              column_name: "(date_date || '-'|| campaign_key)"
          - not_null:
              column_name: "(date_date || '-'|| campaign_key)"

   

       - name: criteo
         identifier: raw_gz_criteo
         columns : 
         - name: date_date
         - name: paid_source
         - name: campaign_key
         - name: camPGN_name 
         - name: ads_cost
         - name: impression
         - name: click
         tests:
          - unique:
              column_name: "(date_date || '-'|| campaign_key)"
          - not_null:
              column_name: "(date_date || '-'|| campaign_key)"


       - name: facebook
         identifier: raw_gz_facebook
         columns : 
         - name: date_date
         - name: paid_source
         - name: campaign_key
         - name: camPGN_name 
         - name: ads_cost
         - name: impression
         - name: click
         tests:
          - unique:
              column_name: "(date_date || '-'|| campaign_key)"
          - not_null:
              column_name: "(date_date || '-'|| campaign_key)"

      